---
title: 'ETC5523: Communicating with Data'
subtitle: "Tutorial 3 Supp C"
author: "Emi Tanaka"
date: "Week 3"
output: html_document
---

```{css, echo = FALSE}
thead {
  background-color: #006DAE;
  color: white;
}
```


```{r setup, include = FALSE}
library(palmerpenguins)
library(tidyverse)
library(sparkline)
library(DT)
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

# Exploring bill length (mm) of palmer penguins

```{r}
penguins %>% 
  group_by(species) %>% 
  summarise(
    fivenum = list(setNames(as.vector(summary(na.omit(bill_length_mm))),
                   c("Min", "Q1", "Median", "Mean", "Q3", "Max"))),
    distribution = spk_chr(bill_length_mm, type = "box")) %>% 
  unnest_wider(fivenum) %>% 
  datatable(escape = FALSE,
            options = list(paging = FALSE,
                           dom = "t",
                           fnDrawCallback = htmlwidgets::JS(
  '
function(){
  HTMLWidgets.staticRender();
}
'
))) %>% 
  spk_add_deps() %>% 
  formatRound(columns = c("Min", "Q1", "Mean", "Median", "Q3", "Max"), digits = 2)
```

